INSERT OR IGNORE INTO game_items (item_id, name, rarity, item_type, stats, lore, special_ability, craft_recipe, npc_sell_price, collection_req, default_bazaar_price)
VALUES
('nether_wart', 'Nether Wart', 'COMMON', 'ITEM', '{}', '["Alchemy ingredient"]', '', '{}', 5, '{}', 10),
('glass_bottle', 'Glass Bottle', 'COMMON', 'ITEM', '{}', '["Alchemy ingredient"]', '', '{"glass": 3}', 2, '{}', 6),
('glass', 'Glass', 'COMMON', 'ITEM', '{}', '["Crafting material"]', '', '{}', 1, '{}', 2),

('speed_rune', 'Speed Rune', 'COMMON', 'RUNE', '{}', '["Used for crafting talismans"]', '', '{}', 50, '{}', 100),
('strength_rune', 'Strength Rune', 'UNCOMMON', 'RUNE', '{}', '["Used for crafting talismans"]', '', '{}', 100, '{}', 200),
('health_rune', 'Health Rune', 'UNCOMMON', 'RUNE', '{}', '["Used for crafting talismans"]', '', '{}', 100, '{}', 200),
('defense_rune', 'Defense Rune', 'UNCOMMON', 'RUNE', '{}', '["Used for crafting talismans"]', '', '{}', 100, '{}', 200),
('intelligence_rune', 'Intelligence Rune', 'RARE', 'RUNE', '{}', '["Used for crafting talismans"]', '', '{}', 200, '{}', 400),
('crit_damage_rune', 'Crit Damage Rune', 'RARE', 'RUNE', '{}', '["Used for crafting talismans"]', '', '{}', 200, '{}', 400),
('crit_chance_rune', 'Crit Chance Rune', 'RARE', 'RUNE', '{}', '["Used for crafting talismans"]', '', '{}', 200, '{}', 400),
('magic_find_rune', 'Magic Find Rune', 'EPIC', 'RUNE', '{}', '["Used for crafting talismans"]', '', '{}', 500, '{}', 1000),
('ferocity_rune', 'Ferocity Rune', 'EPIC', 'RUNE', '{}', '["Used for crafting talismans"]', '', '{}', 500, '{}', 1000),
('ability_damage_rune', 'Ability Damage Rune', 'LEGENDARY', 'RUNE', '{}', '["Used for crafting talismans"]', '', '{}', 1000, '{}', 2000),
('mining_fortune_rune', 'Mining Fortune Rune', 'RARE', 'RUNE', '{}', '["Used for crafting talismans"]', '', '{}', 200, '{}', 400),
('farming_fortune_rune', 'Farming Fortune Rune', 'RARE', 'RUNE', '{}', '["Used for crafting talismans"]', '', '{}', 200, '{}', 400),
('foraging_fortune_rune', 'Foraging Fortune Rune', 'RARE', 'RUNE', '{}', '["Used for crafting talismans"]', '', '{}', 200, '{}', 400),
('fishing_speed_rune', 'Fishing Speed Rune', 'UNCOMMON', 'RUNE', '{}', '["Used for crafting talismans"]', '', '{}', 100, '{}', 200),
('sea_creature_rune', 'Sea Creature Rune', 'RARE', 'RUNE', '{}', '["Used for crafting talismans"]', '', '{}', 200, '{}', 400),
('pet_luck_rune', 'Pet Luck Rune', 'EPIC', 'RUNE', '{}', '["Used for crafting talismans"]', '', '{}', 500, '{}', 1000),
('true_defense_rune', 'True Defense Rune', 'EPIC', 'RUNE', '{}', '["Used for crafting talismans"]', '', '{}', 500, '{}', 1000),
('attack_speed_rune', 'Attack Speed Rune', 'RARE', 'RUNE', '{}', '["Used for crafting talismans"]', '', '{}', 200, '{}', 400),

('awkward_potion', 'Awkward Potion', 'COMMON', 'POTION', '{}', '["Base for brewing"]', '', '{"nether_wart": 1, "glass_bottle": 3}', 10, '{}', 20),
('speed_potion_1', 'Speed Potion I', 'COMMON', 'POTION', '{}', '["Grants Speed I for 3 minutes"]', '', '{"awkward_potion": 1, "enchanted_sugar": 8}', 50, '{}', 100),
('speed_potion_2', 'Speed Potion II', 'UNCOMMON', 'POTION', '{}', '["Grants Speed II for 3 minutes"]', '', '{"speed_potion_1": 1, "enchanted_sugar": 16}', 100, '{}', 200),
('speed_potion_3', 'Speed Potion III', 'RARE', 'POTION', '{}', '["Grants Speed III for 3 minutes"]', '', '{"speed_potion_2": 1, "enchanted_sugar_cane": 32}', 200, '{}', 400),
('strength_potion_1', 'Strength Potion I', 'COMMON', 'POTION', '{}', '["Grants Strength I for 3 minutes"]', '', '{"awkward_potion": 1, "enchanted_blaze_rod": 8}', 50, '{}', 100),
('strength_potion_2', 'Strength Potion II', 'UNCOMMON', 'POTION', '{}', '["Grants Strength II for 3 minutes"]', '', '{"strength_potion_1": 1, "enchanted_blaze_rod": 16}', 100, '{}', 200),
('strength_potion_3', 'Strength Potion III', 'RARE', 'POTION', '{}', '["Grants Strength III for 3 minutes"]', '', '{"strength_potion_2": 1, "enchanted_magma_cream": 32}', 200, '{}', 400),
('regeneration_potion_1', 'Regeneration Potion I', 'COMMON', 'POTION', '{}', '["Grants Regeneration I for 3 minutes"]', '', '{"awkward_potion": 1, "enchanted_ghast_tear": 8}', 50, '{}', 100),
('regeneration_potion_2', 'Regeneration Potion II', 'UNCOMMON', 'POTION', '{}', '["Grants Regeneration II for 3 minutes"]', '', '{"regeneration_potion_1": 1, "enchanted_ghast_tear": 16}', 100, '{}', 200),
('regeneration_potion_3', 'Regeneration Potion III', 'RARE', 'POTION', '{}', '["Grants Regeneration III for 3 minutes"]', '', '{"regeneration_potion_2": 1, "enchanted_ghast_tear": 32}', 200, '{}', 400),
('defense_potion_1', 'Defense Potion I', 'COMMON', 'POTION', '{}', '["Grants Defense I for 3 minutes"]', '', '{"awkward_potion": 1, "enchanted_iron": 8}', 50, '{}', 100),
('defense_potion_2', 'Defense Potion II', 'UNCOMMON', 'POTION', '{}', '["Grants Defense II for 3 minutes"]', '', '{"defense_potion_1": 1, "enchanted_iron": 16}', 100, '{}', 200),
('defense_potion_3', 'Defense Potion III', 'RARE', 'POTION', '{}', '["Grants Defense III for 3 minutes"]', '', '{"defense_potion_2": 1, "enchanted_iron_block": 32}', 200, '{}', 400),
('critical_potion_1', 'Critical Potion I', 'UNCOMMON', 'POTION', '{}', '["Grants Critical I for 3 minutes"]', '', '{"awkward_potion": 1, "enchanted_flint": 16}', 100, '{}', 200),
('critical_potion_2', 'Critical Potion II', 'RARE', 'POTION', '{}', '["Grants Critical II for 3 minutes"]', '', '{"critical_potion_1": 1, "enchanted_flint": 32}', 200, '{}', 400),
('critical_potion_3', 'Critical Potion III', 'EPIC', 'POTION', '{}', '["Grants Critical III for 3 minutes"]', '', '{"critical_potion_2": 1, "enchanted_quartz": 64}', 500, '{}', 1000),
('magic_find_potion_1', 'Magic Find Potion I', 'RARE', 'POTION', '{}', '["Grants Magic Find I for 3 minutes"]', '', '{"awkward_potion": 1, "enchanted_glowstone": 16}', 200, '{}', 400),
('magic_find_potion_2', 'Magic Find Potion II', 'EPIC', 'POTION', '{}', '["Grants Magic Find II for 3 minutes"]', '', '{"magic_find_potion_1": 1, "enchanted_glowstone": 32}', 500, '{}', 1000),
('magic_find_potion_3', 'Magic Find Potion III', 'LEGENDARY', 'POTION', '{}', '["Grants Magic Find III for 3 minutes"]', '', '{"magic_find_potion_2": 1, "enchanted_glowstone": 64}', 1000, '{}', 2000),
('fishing_potion_1', 'Fishing Potion I', 'COMMON', 'POTION', '{}', '["Grants Fishing I for 3 minutes"]', '', '{"awkward_potion": 1, "raw_fish": 32}', 50, '{}', 100),
('fishing_potion_2', 'Fishing Potion II', 'UNCOMMON', 'POTION', '{}', '["Grants Fishing II for 3 minutes"]', '', '{"fishing_potion_1": 1, "enchanted_prismarine_shard": 16}', 100, '{}', 200),
('fishing_potion_3', 'Fishing Potion III', 'RARE', 'POTION', '{}', '["Grants Fishing III for 3 minutes"]', '', '{"fishing_potion_2": 1, "enchanted_prismarine_crystals": 32}', 200, '{}', 400),
('mining_potion_1', 'Mining Potion I', 'COMMON', 'POTION', '{}', '["Grants Mining I for 3 minutes"]', '', '{"awkward_potion": 1, "enchanted_coal": 8}', 50, '{}', 100),
('mining_potion_2', 'Mining Potion II', 'UNCOMMON', 'POTION', '{}', '["Grants Mining II for 3 minutes"]', '', '{"mining_potion_1": 1, "enchanted_iron": 16}', 100, '{}', 200),
('mining_potion_3', 'Mining Potion III', 'RARE', 'POTION', '{}', '["Grants Mining III for 3 minutes"]', '', '{"mining_potion_2": 1, "enchanted_diamond": 32}', 200, '{}', 400),
('farming_potion_1', 'Farming Potion I', 'COMMON', 'POTION', '{}', '["Grants Farming Fortune I for 3 minutes"]', '', '{"awkward_potion": 1, "enchanted_bread": 8}', 50, '{}', 100),
('farming_potion_2', 'Farming Potion II', 'UNCOMMON', 'POTION', '{}', '["Grants Farming Fortune II for 3 minutes"]', '', '{"farming_potion_1": 1, "enchanted_carrot": 16}', 100, '{}', 200),
('farming_potion_3', 'Farming Potion III', 'RARE', 'POTION', '{}', '["Grants Farming Fortune III for 3 minutes"]', '', '{"farming_potion_2": 1, "golden_carrot": 32}', 200, '{}', 400),
('combat_potion_1', 'Combat Potion I', 'UNCOMMON', 'POTION', '{}', '["Grants Combat XP I for 3 minutes"]', '', '{"awkward_potion": 1, "enchanted_rotten_flesh": 16}', 100, '{}', 200),
('combat_potion_2', 'Combat Potion II', 'RARE', 'POTION', '{}', '["Grants Combat XP II for 3 minutes"]', '', '{"combat_potion_1": 1, "enchanted_bone": 32}', 200, '{}', 400),
('combat_potion_3', 'Combat Potion III', 'EPIC', 'POTION', '{}', '["Grants Combat XP III for 3 minutes"]', '', '{"combat_potion_2": 1, "revenant_flesh": 64}', 500, '{}', 1000),
('intelligence_potion_1', 'Intelligence Potion I', 'UNCOMMON', 'POTION', '{}', '["Grants Intelligence I for 3 minutes"]', '', '{"awkward_potion": 1, "enchanted_lapis": 16}', 100, '{}', 200),
('intelligence_potion_2', 'Intelligence Potion II', 'RARE', 'POTION', '{}', '["Grants Intelligence II for 3 minutes"]', '', '{"intelligence_potion_1": 1, "enchanted_lapis": 32}', 200, '{}', 400),
('intelligence_potion_3', 'Intelligence Potion III', 'EPIC', 'POTION', '{}', '["Grants Intelligence III for 3 minutes"]', '', '{"intelligence_potion_2": 1, "enchanted_lapis_block": 64}', 500, '{}', 1000),
('true_defense_potion_1', 'True Defense Potion I', 'RARE', 'POTION', '{}', '["Grants True Defense I for 3 minutes"]', '', '{"defense_potion_3": 1, "enchanted_obsidian": 32}', 200, '{}', 400),
('true_defense_potion_2', 'True Defense Potion II', 'EPIC', 'POTION', '{}', '["Grants True Defense II for 3 minutes"]', '', '{"true_defense_potion_1": 1, "enchanted_obsidian": 64}', 500, '{}', 1000),
('true_defense_potion_3', 'True Defense Potion III', 'LEGENDARY', 'POTION', '{}', '["Grants True Defense III for 3 minutes"]', '', '{"true_defense_potion_2": 1, "wither_cloak_sword": 1}', 1000, '{}', 2000),
('crit_damage_potion_1', 'Crit Damage Potion I', 'UNCOMMON', 'POTION', '{}', '["Grants Crit Damage I for 3 minutes"]', '', '{"awkward_potion": 1, "enchanted_quartz": 16}', 100, '{}', 200),
('crit_damage_potion_2', 'Crit Damage Potion II', 'RARE', 'POTION', '{}', '["Grants Crit Damage II for 3 minutes"]', '', '{"crit_damage_potion_1": 1, "enchanted_quartz": 32}', 200, '{}', 400),
('crit_damage_potion_3', 'Crit Damage Potion III', 'EPIC', 'POTION', '{}', '["Grants Crit Damage III for 3 minutes"]', '', '{"crit_damage_potion_2": 1, "enchanted_quartz_block": 64}', 500, '{}', 1000),
('ability_damage_potion_1', 'Ability Damage Potion I', 'RARE', 'POTION', '{}', '["Grants Ability Damage I for 3 minutes"]', '', '{"intelligence_potion_3": 1, "enchanted_ender_pearl": 32}', 200, '{}', 400),
('ability_damage_potion_2', 'Ability Damage Potion II', 'EPIC', 'POTION', '{}', '["Grants Ability Damage II for 3 minutes"]', '', '{"ability_damage_potion_1": 1, "enchanted_ender_pearl": 64}', 500, '{}', 1000),
('ability_damage_potion_3', 'Ability Damage Potion III', 'LEGENDARY', 'POTION', '{}', '["Grants Ability Damage III for 3 minutes"]', '', '{"ability_damage_potion_2": 1, "enchanted_eye_of_ender": 64}', 1000, '{}', 2000),
('ferocity_potion_1', 'Ferocity Potion I', 'RARE', 'POTION', '{}', '["Grants Ferocity I for 3 minutes"]', '', '{"strength_potion_3": 1, "enchanted_bone": 32}', 200, '{}', 400),
('ferocity_potion_2', 'Ferocity Potion II', 'EPIC', 'POTION', '{}', '["Grants Ferocity II for 3 minutes"]', '', '{"ferocity_potion_1": 1, "revenant_flesh": 64}', 500, '{}', 1000),
('ferocity_potion_3', 'Ferocity Potion III', 'LEGENDARY', 'POTION', '{}', '["Grants Ferocity III for 3 minutes"]', '', '{"ferocity_potion_2": 1, "wither_essence": 64}', 1000, '{}', 2000),
('pet_luck_potion_1', 'Pet Luck Potion I', 'RARE', 'POTION', '{}', '["Grants Pet Luck I for 3 minutes"]', '', '{"magic_find_potion_2": 1, "enchanted_bone": 32}', 200, '{}', 400),
('pet_luck_potion_2', 'Pet Luck Potion II', 'EPIC', 'POTION', '{}', '["Grants Pet Luck II for 3 minutes"]', '', '{"pet_luck_potion_1": 1, "wolf_tooth": 64}', 500, '{}', 1000),
('pet_luck_potion_3', 'Pet Luck Potion III', 'LEGENDARY', 'POTION', '{}', '["Grants Pet Luck III for 3 minutes"]', '', '{"pet_luck_potion_2": 1, "summoning_eye": 8}', 1000, '{}', 2000),
('foraging_potion_1', 'Foraging Potion I', 'COMMON', 'POTION', '{}', '["Grants Foraging Fortune I for 3 minutes"]', '', '{"awkward_potion": 1, "enchanted_oak_wood": 8}', 50, '{}', 100),
('foraging_potion_2', 'Foraging Potion II', 'UNCOMMON', 'POTION', '{}', '["Grants Foraging Fortune II for 3 minutes"]', '', '{"foraging_potion_1": 1, "enchanted_oak_wood": 16}', 100, '{}', 200),
('foraging_potion_3', 'Foraging Potion III', 'RARE', 'POTION', '{}', '["Grants Foraging Fortune III for 3 minutes"]', '', '{"foraging_potion_2": 1, "enchanted_jungle_wood": 32}', 200, '{}', 400),
('attack_speed_potion_1', 'Attack Speed Potion I', 'UNCOMMON', 'POTION', '{}', '["Grants Attack Speed I for 3 minutes"]', '', '{"speed_potion_2": 1, "enchanted_redstone": 16}', 100, '{}', 200),
('attack_speed_potion_2', 'Attack Speed Potion II', 'RARE', 'POTION', '{}', '["Grants Attack Speed II for 3 minutes"]', '', '{"attack_speed_potion_1": 1, "enchanted_redstone": 32}', 200, '{}', 400),
('attack_speed_potion_3', 'Attack Speed Potion III', 'EPIC', 'POTION', '{}', '["Grants Attack Speed III for 3 minutes"]', '', '{"attack_speed_potion_2": 1, "enchanted_redstone_block": 64}', 500, '{}', 1000),

('speed_talisman', 'Speed Talisman', 'COMMON', 'TALISMAN', '{"speed": 5}', '["Increases speed"]', '', '{"speed_rune": 4, "enchanted_sugar": 16}', 100, '{}', 200),
('strength_talisman', 'Strength Talisman', 'UNCOMMON', 'TALISMAN', '{"strength": 5}', '["Increases strength"]', '', '{"strength_rune": 4, "enchanted_blaze_rod": 16}', 200, '{}', 400),
('health_talisman', 'Health Talisman', 'UNCOMMON', 'TALISMAN', '{"health": 20}', '["Increases health"]', '', '{"health_rune": 4, "enchanted_ghast_tear": 16}', 200, '{}', 400),
('defense_talisman', 'Defense Talisman', 'UNCOMMON', 'TALISMAN', '{"defense": 10}', '["Increases defense"]', '', '{"defense_rune": 4, "enchanted_iron": 16}', 200, '{}', 400),
('intelligence_talisman', 'Intelligence Talisman', 'RARE', 'TALISMAN', '{"intelligence": 10}', '["Increases intelligence"]', '', '{"intelligence_rune": 4, "enchanted_lapis": 32}', 400, '{}', 800),
('crit_damage_talisman', 'Critical Damage Talisman', 'RARE', 'TALISMAN', '{"crit_damage": 10}', '["Increases crit damage"]', '', '{"crit_damage_rune": 4, "enchanted_quartz": 32}', 400, '{}', 800),
('crit_chance_talisman', 'Critical Chance Talisman', 'RARE', 'TALISMAN', '{"crit_chance": 3}', '["Increases crit chance"]', '', '{"crit_chance_rune": 4, "enchanted_flint": 32}', 400, '{}', 800),
('magic_find_talisman', 'Magic Find Talisman', 'EPIC', 'TALISMAN', '{"magic_find": 5}', '["Increases magic find"]', '', '{"magic_find_rune": 4, "enchanted_glowstone": 64}', 1000, '{}', 2000),
('ferocity_talisman', 'Ferocity Talisman', 'EPIC', 'TALISMAN', '{"ferocity": 5}', '["Increases ferocity"]', '', '{"ferocity_rune": 4, "enchanted_bone": 64}', 1000, '{}', 2000),
('ability_damage_talisman', 'Ability Damage Talisman', 'LEGENDARY', 'TALISMAN', '{"ability_damage": 10}', '["Increases ability damage"]', '', '{"ability_damage_rune": 4, "nether_star": 8}', 2000, '{}', 4000),
('mining_fortune_talisman', 'Mining Fortune Talisman', 'RARE', 'TALISMAN', '{"mining_fortune": 10}', '["Increases mining fortune"]', '', '{"mining_fortune_rune": 4, "enchanted_diamond": 32}', 400, '{}', 800),
('farming_fortune_talisman', 'Farming Fortune Talisman', 'RARE', 'TALISMAN', '{"farming_fortune": 10}', '["Increases farming fortune"]', '', '{"farming_fortune_rune": 4, "enchanted_bread": 32}', 400, '{}', 800),
('foraging_fortune_talisman', 'Foraging Fortune Talisman', 'RARE', 'TALISMAN', '{"foraging_fortune": 10}', '["Increases foraging fortune"]', '', '{"foraging_fortune_rune": 4, "enchanted_oak_wood": 32}', 400, '{}', 800),
('fishing_speed_talisman', 'Fishing Speed Talisman', 'UNCOMMON', 'TALISMAN', '{"fishing_speed": 5}', '["Increases fishing speed"]', '', '{"fishing_speed_rune": 4, "raw_fish": 64}', 200, '{}', 400),
('pet_luck_talisman', 'Pet Luck Talisman', 'EPIC', 'TALISMAN', '{"pet_luck": 5}', '["Increases pet luck"]', '', '{"pet_luck_rune": 4, "enchanted_bone": 64}', 1000, '{}', 2000),
('sea_creature_chance_talisman', 'Sea Creature Chance Talisman', 'RARE', 'TALISMAN', '{"sea_creature_chance": 3}', '["Increases sea creature chance"]', '', '{"sea_creature_rune": 4, "enchanted_prismarine_shard": 32}', 400, '{}', 800),
('true_defense_talisman', 'True Defense Talisman', 'EPIC', 'TALISMAN', '{"true_defense": 5}', '["Increases true defense"]', '', '{"true_defense_rune": 4, "enchanted_obsidian": 64}', 1000, '{}', 2000),
('attack_speed_talisman', 'Attack Speed Talisman', 'RARE', 'TALISMAN', '{"attack_speed": 5}', '["Increases attack speed"]', '', '{"attack_speed_rune": 4, "enchanted_redstone": 32}', 400, '{}', 800);

INSERT OR IGNORE INTO crafting_recipes (recipe_id, output_item, ingredients, output_amount)
VALUES
('glass_bottle_recipe', 'glass_bottle', '{"glass": 3}', 1),
('awkward_potion_recipe', 'awkward_potion', '{"nether_wart": 1, "glass_bottle": 3}', 1),
('speed_potion_1_recipe', 'speed_potion_1', '{"awkward_potion": 1, "enchanted_sugar": 8}', 1),
('speed_potion_2_recipe', 'speed_potion_2', '{"speed_potion_1": 1, "enchanted_sugar": 16}', 1),
('speed_potion_3_recipe', 'speed_potion_3', '{"speed_potion_2": 1, "enchanted_sugar_cane": 32}', 1),
('strength_potion_1_recipe', 'strength_potion_1', '{"awkward_potion": 1, "enchanted_blaze_rod": 8}', 1),
('strength_potion_2_recipe', 'strength_potion_2', '{"strength_potion_1": 1, "enchanted_blaze_rod": 16}', 1),
('strength_potion_3_recipe', 'strength_potion_3', '{"strength_potion_2": 1, "enchanted_magma_cream": 32}', 1),
('regeneration_potion_1_recipe', 'regeneration_potion_1', '{"awkward_potion": 1, "enchanted_ghast_tear": 8}', 1),
('regeneration_potion_2_recipe', 'regeneration_potion_2', '{"regeneration_potion_1": 1, "enchanted_ghast_tear": 16}', 1),
('regeneration_potion_3_recipe', 'regeneration_potion_3', '{"regeneration_potion_2": 1, "enchanted_ghast_tear": 32}', 1),
('defense_potion_1_recipe', 'defense_potion_1', '{"awkward_potion": 1, "enchanted_iron": 8}', 1),
('defense_potion_2_recipe', 'defense_potion_2', '{"defense_potion_1": 1, "enchanted_iron": 16}', 1),
('defense_potion_3_recipe', 'defense_potion_3', '{"defense_potion_2": 1, "enchanted_iron_block": 32}', 1),
('critical_potion_1_recipe', 'critical_potion_1', '{"awkward_potion": 1, "enchanted_flint": 16}', 1),
('critical_potion_2_recipe', 'critical_potion_2', '{"critical_potion_1": 1, "enchanted_flint": 32}', 1),
('critical_potion_3_recipe', 'critical_potion_3', '{"critical_potion_2": 1, "enchanted_quartz": 64}', 1),
('magic_find_potion_1_recipe', 'magic_find_potion_1', '{"awkward_potion": 1, "enchanted_glowstone": 16}', 1),
('magic_find_potion_2_recipe', 'magic_find_potion_2', '{"magic_find_potion_1": 1, "enchanted_glowstone": 32}', 1),
('magic_find_potion_3_recipe', 'magic_find_potion_3', '{"magic_find_potion_2": 1, "enchanted_glowstone": 64}', 1),
('fishing_potion_1_recipe', 'fishing_potion_1', '{"awkward_potion": 1, "raw_fish": 32}', 1),
('fishing_potion_2_recipe', 'fishing_potion_2', '{"fishing_potion_1": 1, "enchanted_prismarine_shard": 16}', 1),
('fishing_potion_3_recipe', 'fishing_potion_3', '{"fishing_potion_2": 1, "enchanted_prismarine_crystals": 32}', 1),
('mining_potion_1_recipe', 'mining_potion_1', '{"awkward_potion": 1, "enchanted_coal": 8}', 1),
('mining_potion_2_recipe', 'mining_potion_2', '{"mining_potion_1": 1, "enchanted_iron": 16}', 1),
('mining_potion_3_recipe', 'mining_potion_3', '{"mining_potion_2": 1, "enchanted_diamond": 32}', 1),
('farming_potion_1_recipe', 'farming_potion_1', '{"awkward_potion": 1, "enchanted_bread": 8}', 1),
('farming_potion_2_recipe', 'farming_potion_2', '{"farming_potion_1": 1, "enchanted_carrot": 16}', 1),
('farming_potion_3_recipe', 'farming_potion_3', '{"farming_potion_2": 1, "golden_carrot": 32}', 1),
('combat_potion_1_recipe', 'combat_potion_1', '{"awkward_potion": 1, "enchanted_rotten_flesh": 16}', 1),
('combat_potion_2_recipe', 'combat_potion_2', '{"combat_potion_1": 1, "enchanted_bone": 32}', 1),
('combat_potion_3_recipe', 'combat_potion_3', '{"combat_potion_2": 1, "revenant_flesh": 64}', 1),
('intelligence_potion_1_recipe', 'intelligence_potion_1', '{"awkward_potion": 1, "enchanted_lapis": 16}', 1),
('intelligence_potion_2_recipe', 'intelligence_potion_2', '{"intelligence_potion_1": 1, "enchanted_lapis": 32}', 1),
('intelligence_potion_3_recipe', 'intelligence_potion_3', '{"intelligence_potion_2": 1, "enchanted_lapis_block": 64}', 1),
('true_defense_potion_1_recipe', 'true_defense_potion_1', '{"defense_potion_3": 1, "enchanted_obsidian": 32}', 1),
('true_defense_potion_2_recipe', 'true_defense_potion_2', '{"true_defense_potion_1": 1, "enchanted_obsidian": 64}', 1),
('true_defense_potion_3_recipe', 'true_defense_potion_3', '{"true_defense_potion_2": 1, "wither_cloak_sword": 1}', 1),
('crit_damage_potion_1_recipe', 'crit_damage_potion_1', '{"awkward_potion": 1, "enchanted_quartz": 16}', 1),
('crit_damage_potion_2_recipe', 'crit_damage_potion_2', '{"crit_damage_potion_1": 1, "enchanted_quartz": 32}', 1),
('crit_damage_potion_3_recipe', 'crit_damage_potion_3', '{"crit_damage_potion_2": 1, "enchanted_quartz_block": 64}', 1),
('ability_damage_potion_1_recipe', 'ability_damage_potion_1', '{"intelligence_potion_3": 1, "enchanted_ender_pearl": 32}', 1),
('ability_damage_potion_2_recipe', 'ability_damage_potion_2', '{"ability_damage_potion_1": 1, "enchanted_ender_pearl": 64}', 1),
('ability_damage_potion_3_recipe', 'ability_damage_potion_3', '{"ability_damage_potion_2": 1, "enchanted_eye_of_ender": 64}', 1),
('ferocity_potion_1_recipe', 'ferocity_potion_1', '{"strength_potion_3": 1, "enchanted_bone": 32}', 1),
('ferocity_potion_2_recipe', 'ferocity_potion_2', '{"ferocity_potion_1": 1, "revenant_flesh": 64}', 1),
('ferocity_potion_3_recipe', 'ferocity_potion_3', '{"ferocity_potion_2": 1, "wither_essence": 64}', 1),
('pet_luck_potion_1_recipe', 'pet_luck_potion_1', '{"magic_find_potion_2": 1, "enchanted_bone": 32}', 1),
('pet_luck_potion_2_recipe', 'pet_luck_potion_2', '{"pet_luck_potion_1": 1, "wolf_tooth": 64}', 1),
('pet_luck_potion_3_recipe', 'pet_luck_potion_3', '{"pet_luck_potion_2": 1, "summoning_eye": 8}', 1),
('foraging_potion_1_recipe', 'foraging_potion_1', '{"awkward_potion": 1, "enchanted_oak_wood": 8}', 1),
('foraging_potion_2_recipe', 'foraging_potion_2', '{"foraging_potion_1": 1, "enchanted_oak_wood": 16}', 1),
('foraging_potion_3_recipe', 'foraging_potion_3', '{"foraging_potion_2": 1, "enchanted_jungle_wood": 32}', 1),
('attack_speed_potion_1_recipe', 'attack_speed_potion_1', '{"speed_potion_2": 1, "enchanted_redstone": 16}', 1),
('attack_speed_potion_2_recipe', 'attack_speed_potion_2', '{"attack_speed_potion_1": 1, "enchanted_redstone": 32}', 1),
('attack_speed_potion_3_recipe', 'attack_speed_potion_3', '{"attack_speed_potion_2": 1, "enchanted_redstone_block": 64}', 1),
('speed_talisman_recipe', 'speed_talisman', '{"speed_rune": 4, "enchanted_sugar": 16}', 1),
('strength_talisman_recipe', 'strength_talisman', '{"strength_rune": 4, "enchanted_blaze_rod": 16}', 1),
('health_talisman_recipe', 'health_talisman', '{"health_rune": 4, "enchanted_ghast_tear": 16}', 1),
('defense_talisman_recipe', 'defense_talisman', '{"defense_rune": 4, "enchanted_iron": 16}', 1),
('intelligence_talisman_recipe', 'intelligence_talisman', '{"intelligence_rune": 4, "enchanted_lapis": 32}', 1),
('crit_damage_talisman_recipe', 'crit_damage_talisman', '{"crit_damage_rune": 4, "enchanted_quartz": 32}', 1),
('crit_chance_talisman_recipe', 'crit_chance_talisman', '{"crit_chance_rune": 4, "enchanted_flint": 32}', 1),
('magic_find_talisman_recipe', 'magic_find_talisman', '{"magic_find_rune": 4, "enchanted_glowstone": 64}', 1),
('ferocity_talisman_recipe', 'ferocity_talisman', '{"ferocity_rune": 4, "enchanted_bone": 64}', 1),
('ability_damage_talisman_recipe', 'ability_damage_talisman', '{"ability_damage_rune": 4, "nether_star": 8}', 1),
('mining_fortune_talisman_recipe', 'mining_fortune_talisman', '{"mining_fortune_rune": 4, "enchanted_diamond": 32}', 1),
('farming_fortune_talisman_recipe', 'farming_fortune_talisman', '{"farming_fortune_rune": 4, "enchanted_bread": 32}', 1),
('foraging_fortune_talisman_recipe', 'foraging_fortune_talisman', '{"foraging_fortune_rune": 4, "enchanted_oak_wood": 32}', 1),
('fishing_speed_talisman_recipe', 'fishing_speed_talisman', '{"fishing_speed_rune": 4, "raw_fish": 64}', 1),
('pet_luck_talisman_recipe', 'pet_luck_talisman', '{"pet_luck_rune": 4, "enchanted_bone": 64}', 1),
('sea_creature_chance_talisman_recipe', 'sea_creature_chance_talisman', '{"sea_creature_rune": 4, "enchanted_prismarine_shard": 32}', 1),
('true_defense_talisman_recipe', 'true_defense_talisman', '{"true_defense_rune": 4, "enchanted_obsidian": 64}', 1),
('attack_speed_talisman_recipe', 'attack_speed_talisman', '{"attack_speed_rune": 4, "enchanted_redstone": 32}', 1);
