INSERT OR IGNORE INTO bestiary_rewards (mob_id, level, reward_type, reward_value) VALUES
('enderman', 2, 'intelligence', 10),
('enderman', 3, 'crit_damage', 5),
('enderman', 4, 'crit_damage', 10),
('enderman', 5, 'intelligence', 15),
('enderman', 6, 'health', 15),
('enderman', 7, 'strength', 8),
('enderman', 8, 'crit_damage', 15),
('enderman', 9, 'intelligence', 25),

('blaze', 1, 'strength', 3),
('blaze', 2, 'strength', 5),
('blaze', 3, 'crit_damage', 8),
('blaze', 4, 'defense', 5),
('blaze', 5, 'health', 15),
('blaze', 6, 'strength', 8),
('blaze', 7, 'crit_damage', 12),
('blaze', 8, 'defense', 10),
('blaze', 9, 'strength', 15),

('magma_cube', 1, 'defense', 2),
('magma_cube', 2, 'defense', 4),
('magma_cube', 3, 'health', 10),
('magma_cube', 4, 'defense', 6),
('magma_cube', 5, 'health', 20),
('magma_cube', 6, 'defense', 8),
('magma_cube', 7, 'health', 30),
('magma_cube', 8, 'defense', 12),
('magma_cube', 9, 'health', 50),

('wither_skeleton', 1, 'strength', 4),
('wither_skeleton', 2, 'crit_damage', 8),
('wither_skeleton', 3, 'strength', 6),
('wither_skeleton', 4, 'crit_damage', 12),
('wither_skeleton', 5, 'defense', 8),
('wither_skeleton', 6, 'strength', 10),
('wither_skeleton', 7, 'crit_damage', 18),
('wither_skeleton', 8, 'health', 40),
('wither_skeleton', 9, 'strength', 20),

('cave_spider', 1, 'speed', 2),
('cave_spider', 2, 'crit_chance', 2),
('cave_spider', 3, 'strength', 3),
('cave_spider', 4, 'speed', 3),
('cave_spider', 5, 'crit_damage', 10),
('cave_spider', 6, 'defense', 5),
('cave_spider', 7, 'strength', 6),
('cave_spider', 8, 'crit_damage', 15),
('cave_spider', 9, 'speed', 5),

('lapis_zombie', 1, 'intelligence', 3),
('lapis_zombie', 2, 'health', 8),
('lapis_zombie', 3, 'intelligence', 5),
('lapis_zombie', 4, 'defense', 4),
('lapis_zombie', 5, 'intelligence', 8),
('lapis_zombie', 6, 'health', 15),
('lapis_zombie', 7, 'strength', 5),
('lapis_zombie', 8, 'intelligence', 12),
('lapis_zombie', 9, 'health', 25),

('broodfather', 1, 'strength', 5),
('broodfather', 2, 'crit_damage', 10),
('broodfather', 3, 'health', 20),
('broodfather', 4, 'strength', 8),
('broodfather', 5, 'crit_damage', 15),
('broodfather', 6, 'defense', 10),
('broodfather', 7, 'strength', 12),
('broodfather', 8, 'crit_damage', 25),
('broodfather', 9, 'health', 50),

('spider_jockey', 1, 'crit_chance', 2),
('spider_jockey', 2, 'strength', 4),
('spider_jockey', 3, 'crit_damage', 8),
('spider_jockey', 4, 'speed', 3),
('spider_jockey', 5, 'strength', 6),
('spider_jockey', 6, 'crit_damage', 12),
('spider_jockey', 7, 'health', 18),
('spider_jockey', 8, 'strength', 10),
('spider_jockey', 9, 'crit_damage', 20),

('zealot', 1, 'strength', 5),
('zealot', 2, 'crit_damage', 12),
('zealot', 3, 'intelligence', 10),
('zealot', 4, 'strength', 8),
('zealot', 5, 'crit_damage', 18),
('zealot', 6, 'health', 25),
('zealot', 7, 'strength', 12),
('zealot', 8, 'crit_damage', 25),
('zealot', 9, 'intelligence', 20),

('ender_dragon', 1, 'strength', 10),
('ender_dragon', 2, 'health', 30),
('ender_dragon', 3, 'crit_damage', 20),
('ender_dragon', 4, 'defense', 15),
('ender_dragon', 5, 'strength', 15),
('ender_dragon', 6, 'crit_damage', 30),
('ender_dragon', 7, 'health', 60),
('ender_dragon', 8, 'strength', 25),
('ender_dragon', 9, 'crit_damage', 50),

('ghast', 1, 'intelligence', 5),
('ghast', 2, 'defense', 5),
('ghast', 3, 'intelligence', 8),
('ghast', 4, 'health', 20),
('ghast', 5, 'intelligence', 12),
('ghast', 6, 'defense', 10),
('ghast', 7, 'intelligence', 18),
('ghast', 8, 'health', 35),
('ghast', 9, 'intelligence', 30),

('piglin_brute', 1, 'strength', 6),
('piglin_brute', 2, 'defense', 6),
('piglin_brute', 3, 'strength', 10),
('piglin_brute', 4, 'health', 25),
('piglin_brute', 5, 'defense', 12),
('piglin_brute', 6, 'strength', 15),
('piglin_brute', 7, 'crit_damage', 20),
('piglin_brute', 8, 'health', 40),
('piglin_brute', 9, 'strength', 25),

('wither', 1, 'strength', 8),
('wither', 2, 'health', 35),
('wither', 3, 'crit_damage', 25),
('wither', 4, 'defense', 15),
('wither', 5, 'strength', 15),
('wither', 6, 'crit_damage', 35),
('wither', 7, 'health', 70),
('wither', 8, 'strength', 30),
('wither', 9, 'crit_damage', 60),

('redstone_pigman', 1, 'attack_speed', 2),
('redstone_pigman', 2, 'strength', 4),
('redstone_pigman', 3, 'attack_speed', 3),
('redstone_pigman', 4, 'crit_damage', 10),
('redstone_pigman', 5, 'strength', 7),
('redstone_pigman', 6, 'attack_speed', 5),
('redstone_pigman', 7, 'crit_damage', 15),
('redstone_pigman', 8, 'strength', 12),
('redstone_pigman', 9, 'attack_speed', 8),

('emerald_slime', 1, 'magic_find', 1),
('emerald_slime', 2, 'defense', 5),
('emerald_slime', 3, 'magic_find', 2),
('emerald_slime', 4, 'health', 15),
('emerald_slime', 5, 'magic_find', 3),
('emerald_slime', 6, 'defense', 10),
('emerald_slime', 7, 'magic_find', 5),
('emerald_slime', 8, 'health', 30),
('emerald_slime', 9, 'magic_find', 10);
