CREATE TABLE IF NOT EXISTS potion_effects (
    potion_id TEXT PRIMARY KEY,
    effect_type TEXT NOT NULL,
    stat_name TEXT,
    amount INTEGER NOT NULL,
    duration INTEGER,
    special_effects TEXT
);

INSERT OR REPLACE INTO potion_effects (potion_id, effect_type, stat_name, amount, duration, special_effects) VALUES
('speed_potion_1', 'stat_boost', 'speed', 10, 180, NULL),
('speed_potion_2', 'stat_boost', 'speed', 20, 180, NULL),
('speed_potion_3', 'stat_boost', 'speed', 30, 180, NULL),
('strength_potion_1', 'stat_boost', 'strength', 10, 180, NULL),
('strength_potion_2', 'stat_boost', 'strength', 20, 180, NULL),
('strength_potion_3', 'stat_boost', 'strength', 30, 180, NULL),
('regeneration_potion_1', 'stat_boost', 'health_regen', 5, 180, NULL),
('regeneration_potion_2', 'stat_boost', 'health_regen', 10, 180, NULL),
('regeneration_potion_3', 'stat_boost', 'health_regen', 15, 180, NULL),
('defense_potion_1', 'stat_boost', 'defense', 15, 180, NULL),
('defense_potion_2', 'stat_boost', 'defense', 30, 180, NULL),
('defense_potion_3', 'stat_boost', 'defense', 45, 180, NULL),
('critical_potion_1', 'stat_boost', 'crit_chance', 5, 180, NULL),
('critical_potion_2', 'stat_boost', 'crit_chance', 10, 180, NULL),
('critical_potion_3', 'stat_boost', 'crit_chance', 15, 180, NULL),
('magic_find_potion_1', 'stat_boost', 'magic_find', 10, 180, NULL),
('magic_find_potion_2', 'stat_boost', 'magic_find', 20, 180, NULL),
('magic_find_potion_3', 'stat_boost', 'magic_find', 30, 180, NULL),
('fishing_potion_1', 'stat_boost', 'sea_creature_chance', 5, 180, NULL),
('fishing_potion_2', 'stat_boost', 'sea_creature_chance', 10, 180, NULL),
('fishing_potion_3', 'stat_boost', 'sea_creature_chance', 15, 180, NULL),
('mining_potion_1', 'stat_boost', 'mining_speed', 10, 180, NULL),
('mining_potion_2', 'stat_boost', 'mining_speed', 20, 180, NULL),
('mining_potion_3', 'stat_boost', 'mining_speed', 30, 180, NULL),
('farming_potion_1', 'stat_boost', 'farming_fortune', 10, 180, NULL),
('farming_potion_2', 'stat_boost', 'farming_fortune', 20, 180, NULL),
('farming_potion_3', 'stat_boost', 'farming_fortune', 30, 180, NULL),
('combat_potion_1', 'stat_boost', 'combat_xp_boost', 10, 180, NULL),
('combat_potion_2', 'stat_boost', 'combat_xp_boost', 20, 180, NULL),
('combat_potion_3', 'stat_boost', 'combat_xp_boost', 30, 180, NULL),
('intelligence_potion_1', 'stat_boost', 'intelligence', 15, 180, NULL),
('intelligence_potion_2', 'stat_boost', 'intelligence', 30, 180, NULL),
('intelligence_potion_3', 'stat_boost', 'intelligence', 50, 180, NULL),
('true_defense_potion_1', 'stat_boost', 'true_defense', 10, 180, NULL),
('true_defense_potion_2', 'stat_boost', 'true_defense', 20, 180, NULL),
('true_defense_potion_3', 'stat_boost', 'true_defense', 30, 180, NULL),
('crit_damage_potion_1', 'stat_boost', 'crit_damage', 15, 180, NULL),
('crit_damage_potion_2', 'stat_boost', 'crit_damage', 30, 180, NULL),
('crit_damage_potion_3', 'stat_boost', 'crit_damage', 50, 180, NULL),
('ability_damage_potion_1', 'stat_boost', 'ability_damage', 10, 180, NULL),
('ability_damage_potion_2', 'stat_boost', 'ability_damage', 20, 180, NULL),
('ability_damage_potion_3', 'stat_boost', 'ability_damage', 30, 180, NULL),
('ferocity_potion_1', 'stat_boost', 'ferocity', 5, 180, NULL),
('ferocity_potion_2', 'stat_boost', 'ferocity', 10, 180, NULL),
('ferocity_potion_3', 'stat_boost', 'ferocity', 15, 180, NULL),
('pet_luck_potion_1', 'stat_boost', 'pet_luck', 5, 180, NULL),
('pet_luck_potion_2', 'stat_boost', 'pet_luck', 10, 180, NULL),
('pet_luck_potion_3', 'stat_boost', 'pet_luck', 15, 180, NULL),
('foraging_potion_1', 'stat_boost', 'foraging_fortune', 10, 180, NULL),
('foraging_potion_2', 'stat_boost', 'foraging_fortune', 20, 180, NULL),
('foraging_potion_3', 'stat_boost', 'foraging_fortune', 30, 180, NULL),
('attack_speed_potion_1', 'stat_boost', 'attack_speed', 5, 180, NULL),
('attack_speed_potion_2', 'stat_boost', 'attack_speed', 10, 180, NULL),
('attack_speed_potion_3', 'stat_boost', 'attack_speed', 15, 180, NULL),
('health_potion', 'instant_heal', NULL, 100, NULL, NULL),
('greater_health_potion', 'instant_heal', NULL, 250, NULL, NULL),
('super_health_potion', 'instant_heal', NULL, 500, NULL, NULL),
('ultimate_health_potion', 'instant_heal', NULL, 1000, NULL, NULL),
('god_potion', 'god', NULL, 0, 1200, '{"strength": 50, "defense": 50, "speed": 50, "crit_chance": 15, "crit_damage": 50, "intelligence": 50, "magic_find": 25, "pet_luck": 15, "ferocity": 15, "ability_damage": 30, "true_defense": 25, "mining_speed": 50, "mining_fortune": 50, "farming_fortune": 50, "foraging_fortune": 50, "fishing_speed": 50, "sea_creature_chance": 25}');
