ALTER TABLE weapon_stats ADD COLUMN combat_drop_yield_multiplier REAL DEFAULT 1.0;
ALTER TABLE armor_stats ADD COLUMN combat_drop_yield_multiplier REAL DEFAULT 1.0;

UPDATE weapon_stats SET combat_drop_yield_multiplier = 1.0 WHERE item_id = 'wooden_sword';
UPDATE weapon_stats SET combat_drop_yield_multiplier = 1.0 WHERE item_id = 'stone_sword';
UPDATE weapon_stats SET combat_drop_yield_multiplier = 1.1 WHERE item_id = 'iron_sword';
UPDATE weapon_stats SET combat_drop_yield_multiplier = 1.2 WHERE item_id = 'diamond_sword';
UPDATE weapon_stats SET combat_drop_yield_multiplier = 1.3 WHERE item_id = 'gold_sword';
UPDATE weapon_stats SET combat_drop_yield_multiplier = 1.5 WHERE item_id = 'emerald_blade';
UPDATE weapon_stats SET combat_drop_yield_multiplier = 1.8 WHERE item_id = 'aspect_of_the_jerry';
UPDATE weapon_stats SET combat_drop_yield_multiplier = 2.0 WHERE item_id = 'aspect_of_the_end';
UPDATE weapon_stats SET combat_drop_yield_multiplier = 2.2 WHERE item_id = 'zombie_sword';
UPDATE weapon_stats SET combat_drop_yield_multiplier = 2.5 WHERE item_id = 'rogue_sword';
UPDATE weapon_stats SET combat_drop_yield_multiplier = 2.7 WHERE item_id = 'undead_sword';
UPDATE weapon_stats SET combat_drop_yield_multiplier = 3.0 WHERE item_id = 'raider_axe';
UPDATE weapon_stats SET combat_drop_yield_multiplier = 3.2 WHERE item_id = 'spider_sword';
UPDATE weapon_stats SET combat_drop_yield_multiplier = 3.5 WHERE item_id = 'fancy_sword';
UPDATE weapon_stats SET combat_drop_yield_multiplier = 3.7 WHERE item_id = 'hunter_knife';
UPDATE weapon_stats SET combat_drop_yield_multiplier = 4.0 WHERE item_id = 'golem_sword';
UPDATE weapon_stats SET combat_drop_yield_multiplier = 4.2 WHERE item_id = 'ember_rod';
UPDATE weapon_stats SET combat_drop_yield_multiplier = 4.5 WHERE item_id = 'frozen_scythe';
UPDATE weapon_stats SET combat_drop_yield_multiplier = 4.7 WHERE item_id = 'flaming_sword';
UPDATE weapon_stats SET combat_drop_yield_multiplier = 5.0 WHERE item_id = 'leaping_sword';
UPDATE weapon_stats SET combat_drop_yield_multiplier = 5.2 WHERE item_id = 'prismarine_blade';
UPDATE weapon_stats SET combat_drop_yield_multiplier = 5.5 WHERE item_id = 'cleaver';
UPDATE weapon_stats SET combat_drop_yield_multiplier = 5.7 WHERE item_id = 'silver_fang';
UPDATE weapon_stats SET combat_drop_yield_multiplier = 6.0 WHERE item_id = 'thick_aspect_of_the_jerry';
UPDATE weapon_stats SET combat_drop_yield_multiplier = 6.2 WHERE item_id = 'thick_aspect_of_the_end';
UPDATE weapon_stats SET combat_drop_yield_multiplier = 6.5 WHERE item_id = 'pigman_sword';
UPDATE weapon_stats SET combat_drop_yield_multiplier = 6.7 WHERE item_id = 'crimson_blade';
UPDATE weapon_stats SET combat_drop_yield_multiplier = 7.0 WHERE item_id = 'tacticians_sword';
UPDATE weapon_stats SET combat_drop_yield_multiplier = 7.2 WHERE item_id = 'void_sword';
UPDATE weapon_stats SET combat_drop_yield_multiplier = 7.5 WHERE item_id = 'end_sword';
UPDATE weapon_stats SET combat_drop_yield_multiplier = 7.7 WHERE item_id = 'yeti_sword';
UPDATE weapon_stats SET combat_drop_yield_multiplier = 8.0 WHERE item_id = 'ender_sword';
UPDATE weapon_stats SET combat_drop_yield_multiplier = 8.2 WHERE item_id = 'fabled_sword';
UPDATE weapon_stats SET combat_drop_yield_multiplier = 8.5 WHERE item_id = 'ornate_zombie_sword';
UPDATE weapon_stats SET combat_drop_yield_multiplier = 8.7 WHERE item_id = 'aurora_sword';
UPDATE weapon_stats SET combat_drop_yield_multiplier = 9.0 WHERE item_id = 'revenant_falchion';
UPDATE weapon_stats SET combat_drop_yield_multiplier = 9.2 WHERE item_id = 'dark_claymore';
UPDATE weapon_stats SET combat_drop_yield_multiplier = 9.5 WHERE item_id = 'glacial_scythe';
UPDATE weapon_stats SET combat_drop_yield_multiplier = 10.0 WHERE item_id = 'pooch_sword';
UPDATE weapon_stats SET combat_drop_yield_multiplier = 10.2 WHERE item_id = 'molten_edge';
UPDATE weapon_stats SET combat_drop_yield_multiplier = 10.5 WHERE item_id = 'thick_scorpion_foil';
UPDATE weapon_stats SET combat_drop_yield_multiplier = 11.0 WHERE item_id = 'shaman_sword';
UPDATE weapon_stats SET combat_drop_yield_multiplier = 11.5 WHERE item_id = 'reaper_sword';
UPDATE weapon_stats SET combat_drop_yield_multiplier = 12.0 WHERE item_id = 'aspect_of_the_dragons';
UPDATE weapon_stats SET combat_drop_yield_multiplier = 12.5 WHERE item_id = 'midas_sword';
UPDATE weapon_stats SET combat_drop_yield_multiplier = 13.0 WHERE item_id = 'livid_dagger';
UPDATE weapon_stats SET combat_drop_yield_multiplier = 13.5 WHERE item_id = 'wither_cloak_sword';
UPDATE weapon_stats SET combat_drop_yield_multiplier = 14.0 WHERE item_id = 'shadow_fury';
UPDATE weapon_stats SET combat_drop_yield_multiplier = 14.5 WHERE item_id = 'reaper_scythe';
UPDATE weapon_stats SET combat_drop_yield_multiplier = 15.0 WHERE item_id = 'flower_of_truth';
UPDATE weapon_stats SET combat_drop_yield_multiplier = 15.5 WHERE item_id = 'voidwalker_katana';
UPDATE weapon_stats SET combat_drop_yield_multiplier = 16.0 WHERE item_id = 'giants_sword';
UPDATE weapon_stats SET combat_drop_yield_multiplier = 16.5 WHERE item_id = 'atomsplit_katana';
UPDATE weapon_stats SET combat_drop_yield_multiplier = 17.0 WHERE item_id = 'necron_blade';
UPDATE weapon_stats SET combat_drop_yield_multiplier = 18.0 WHERE item_id = 'valkyrie';
UPDATE weapon_stats SET combat_drop_yield_multiplier = 19.0 WHERE item_id = 'astraea';
UPDATE weapon_stats SET combat_drop_yield_multiplier = 20.0 WHERE item_id = 'hyperion';
UPDATE weapon_stats SET combat_drop_yield_multiplier = 20.0 WHERE item_id = 'scylla';

UPDATE weapon_stats SET combat_drop_yield_multiplier = 1.0 WHERE item_id = 'wooden_bow';
UPDATE weapon_stats SET combat_drop_yield_multiplier = 1.1 WHERE item_id = 'bow';
UPDATE weapon_stats SET combat_drop_yield_multiplier = 1.5 WHERE item_id = 'savanna_bow';
UPDATE weapon_stats SET combat_drop_yield_multiplier = 2.0 WHERE item_id = 'ender_bow';
UPDATE weapon_stats SET combat_drop_yield_multiplier = 2.5 WHERE item_id = 'explosive_bow';
UPDATE weapon_stats SET combat_drop_yield_multiplier = 3.0 WHERE item_id = 'runaans_bow';
UPDATE weapon_stats SET combat_drop_yield_multiplier = 4.0 WHERE item_id = 'hurricane_bow';
UPDATE weapon_stats SET combat_drop_yield_multiplier = 5.0 WHERE item_id = 'magma_bow';
UPDATE weapon_stats SET combat_drop_yield_multiplier = 6.0 WHERE item_id = 'scorpion_bow';
UPDATE weapon_stats SET combat_drop_yield_multiplier = 7.0 WHERE item_id = 'mosquito_bow';
UPDATE weapon_stats SET combat_drop_yield_multiplier = 8.0 WHERE item_id = 'artisanal_shortbow';
UPDATE weapon_stats SET combat_drop_yield_multiplier = 10.0 WHERE item_id = 'last_breath';
UPDATE weapon_stats SET combat_drop_yield_multiplier = 12.0 WHERE item_id = 'juju_shortbow';
UPDATE weapon_stats SET combat_drop_yield_multiplier = 15.0 WHERE item_id = 'terminator';
UPDATE weapon_stats SET combat_drop_yield_multiplier = 20.0 WHERE item_id = 'soul_eater_bow';

UPDATE armor_stats SET combat_drop_yield_multiplier = 1.0 WHERE item_id LIKE 'leather_%';
UPDATE armor_stats SET combat_drop_yield_multiplier = 1.05 WHERE item_id LIKE 'chainmail_%';
UPDATE armor_stats SET combat_drop_yield_multiplier = 1.1 WHERE item_id LIKE 'iron_%' AND item_id NOT LIKE '%golem%';
UPDATE armor_stats SET combat_drop_yield_multiplier = 1.15 WHERE item_id LIKE 'gold_%' OR item_id LIKE 'golden_%';
UPDATE armor_stats SET combat_drop_yield_multiplier = 1.2 WHERE item_id LIKE 'diamond_%' AND item_id NOT LIKE '%necron%';
UPDATE armor_stats SET combat_drop_yield_multiplier = 1.3 WHERE item_id LIKE 'hardened_diamond_%';
UPDATE armor_stats SET combat_drop_yield_multiplier = 1.4 WHERE item_id LIKE 'ember_%';
UPDATE armor_stats SET combat_drop_yield_multiplier = 1.5 WHERE item_id LIKE 'ender_%' AND item_id NOT LIKE '%dragon%';
UPDATE armor_stats SET combat_drop_yield_multiplier = 1.6 WHERE item_id LIKE 'golem_%';
UPDATE armor_stats SET combat_drop_yield_multiplier = 1.7 WHERE item_id LIKE 'zombie_%' AND item_id NOT LIKE '%revenant%';
UPDATE armor_stats SET combat_drop_yield_multiplier = 1.8 WHERE item_id LIKE 'skeleton_%' AND item_id NOT LIKE '%necron%';
UPDATE armor_stats SET combat_drop_yield_multiplier = 2.0 WHERE item_id LIKE 'spider_%';
UPDATE armor_stats SET combat_drop_yield_multiplier = 2.2 WHERE item_id LIKE 'blaze_%';
UPDATE armor_stats SET combat_drop_yield_multiplier = 2.5 WHERE item_id LIKE 'adaptive_%';
UPDATE armor_stats SET combat_drop_yield_multiplier = 2.7 WHERE item_id LIKE 'strong_%';
UPDATE armor_stats SET combat_drop_yield_multiplier = 3.0 WHERE item_id LIKE 'superior_%';
UPDATE armor_stats SET combat_drop_yield_multiplier = 3.5 WHERE item_id LIKE 'young_dragon_%';
UPDATE armor_stats SET combat_drop_yield_multiplier = 4.0 WHERE item_id LIKE 'wise_dragon_%';
UPDATE armor_stats SET combat_drop_yield_multiplier = 4.5 WHERE item_id LIKE 'old_dragon_%';
UPDATE armor_stats SET combat_drop_yield_multiplier = 5.0 WHERE item_id LIKE 'unstable_dragon_%';
UPDATE armor_stats SET combat_drop_yield_multiplier = 5.5 WHERE item_id LIKE 'protector_dragon_%';
UPDATE armor_stats SET combat_drop_yield_multiplier = 6.0 WHERE item_id LIKE 'strong_dragon_%';
UPDATE armor_stats SET combat_drop_yield_multiplier = 7.0 WHERE item_id LIKE 'superior_dragon_%';
UPDATE armor_stats SET combat_drop_yield_multiplier = 7.0 WHERE item_id LIKE 'holy_%';
UPDATE armor_stats SET combat_drop_yield_multiplier = 8.0 WHERE item_id LIKE 'frozen_%';
UPDATE armor_stats SET combat_drop_yield_multiplier = 9.0 WHERE item_id LIKE 'shadow_assassin_%';
UPDATE armor_stats SET combat_drop_yield_multiplier = 10.0 WHERE item_id LIKE 'necromancer_%';
UPDATE armor_stats SET combat_drop_yield_multiplier = 12.0 WHERE item_id LIKE 'storm_%' AND item_id NOT LIKE '%wither%';
UPDATE armor_stats SET combat_drop_yield_multiplier = 14.0 WHERE item_id LIKE 'goldor_%';
UPDATE armor_stats SET combat_drop_yield_multiplier = 16.0 WHERE item_id LIKE 'necron_%';
UPDATE armor_stats SET combat_drop_yield_multiplier = 18.0 WHERE item_id LIKE 'wither_%';

